# Generated by Django 6.1.1 on 2026-09-28 06:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudySpot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('price_tier', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'verbose_name': 'Study Spot',
                'verbose_name_plural': 'Study Spots',
                'db_table': 'study_spots',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('full_name', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True, null=True)),
                ('preferred_noise_level', models.CharField(blank=True, max_length=20, null=True)),
                ('preferred_outlet_density', models.CharField(blank=True, max_length=20, null=True)),
                ('min_wifi_speed_mbps', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('dark_mode', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='SpotAmenity',
            fields=[
                ('spot', models.OneToOneField(db_column='spot_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='amenities', serialize=False, to='home.studyspot')),
                ('avg_wifi_speed_mbps', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('outlet_density', models.CharField(blank=True, max_length=20, null=True)),
                ('predominant_noise', models.CharField(blank=True, max_length=20, null=True)),
                ('last_recalculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Spot Amenity',
                'verbose_name_plural': 'Spot Amenities',
                'db_table': 'spot_amenities',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('overall_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('outlet_rating', models.CharField(blank=True, max_length=20, null=True)),
                ('noise_level', models.CharField(blank=True, max_length=20, null=True)),
                ('download_speed_mbps', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('upload_speed_mbps', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('review_text', models.TextField(blank=True, null=True)),
                ('spot', models.ForeignKey(db_column='spot_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='home.studyspot')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='home.user')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('spot', models.ForeignKey(db_column='spot_id', on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='home.studyspot')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='home.user')),
            ],
            options={
                'verbose_name': 'Check In',
                'verbose_name_plural': 'Check Ins',
                'db_table': 'check_ins',
            },
        ),
        migrations.CreateModel(
            name='SavedSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('spot', models.ForeignKey(db_column='spot_id', on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='home.studyspot')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='saved_spots', to='home.user')),
            ],
            options={
                'verbose_name': 'Saved Spot',
                'verbose_name_plural': 'Saved Spots',
                'db_table': 'saved_spots',
                'constraints': [models.UniqueConstraint(fields=('user', 'spot'), name='unique_user_saved_spot')],
            },
        ),
    ]
